name: can_bridge
channels:
  - defaults
#  - pytorch
#  - open3d-admin
  - conda-forge
dependencies:
  - pip=21.1.2
#  - matplotlib=3.3.1
#  - pillow=7.2.0
#  - pytorch=1.6.0
#  - torchvision=0.7.0
#  - tensorboard=2.2.1
#  - typing-extensions=3.7.4.3
#  - open3d=0.10.0.0
#  - pandas=1.3.1
#  - scikit-learn=0.24.2
#  - opencv=4.5.2
#  - pyyaml=6.0
  - rospkg=1.3.0
#  - pip:
#      - click==7.1.2
#      - scipy==1.7.0
#      - tqdm==4.61.1
#      - python-can==3.3.4
#      - cantools==37.0.1
#      - pykalman==0.9.5
