services:
    aslan:
        build:
            context: ${HOME}/repos/aslan
            dockerfile: aslan_docker/Dockerfile
        cap_add:
            - SYS_PTRACE
        command: bash -c "./run"
        devices:
            - /dev/bus/usb:/dev/bus/usb
            - /dev/dri:/dev/dri
            - /dev/input:/dev/input
        environment:
            DISPLAY: ${DISPLAY}
            NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics,display
            NVIDIA_VISIBLE_DEVICES: all
            LD_LIBRARY_PATH: /usr/local/nvidia/lib64
        network_mode: host
        privileged: true
        stdin_open: true
        stop_grace_period: 100ms
        tty: true
        user: aslan_user
        volumes:
            - ${HOME}/.ssh:/root/.ssh
            - ${HOME}/repos/aslan:/catkin_ws
            - /lib/modules:/lib/modules
            - /tmp/.X11-unix:/tmp/.X11-unix
        working_dir: /catkin_ws
    carla-sim:
        build:
            context: ${HOME}/repos/openpilot-bridge
            dockerfile: docker/carla.Dockerfile
        command: bash -c "tmux new -d -s default; tmux send-keys './CarlaUE4.sh -nosound -RenderOffScreen -benchmark -fps=20 -quality-level=Low' ENTER; bash"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        environment:
            DISPLAY: :1
        network_mode: host
        privileged: true
        stdin_open: true
        stop_grace_period: 100ms
        tty: true
    openpilot-client:
        build:
            context: ${HOME}/repos/openpilot-bridge
            dockerfile: docker/openpilot.Dockerfile
        command: bash -c "./tmux_script.sh"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        environment:
            DISPLAY: ${DISPLAY}
            QT_X11_NO_MITSHM: 1
            DEBUG_OPENPILOT_BRIDGE: ${DEBUG_OPENPILOT_BRIDGE}
            SHOULD_RUN_OPENPILOT_SIM: ${SHOULD_RUN_OPENPILOT_SIM}
        network_mode: host
        privileged: true
        shm_size: 1G
        stdin_open: true
        stop_grace_period: 100ms
        tty: true
        volumes:
            - ${HOME}/repos/openpilot:/openpilot
            - ${HOME}/repos/openpilot-bridge:/openpilot-bridge
            - /tmp/.X11-unix:/tmp/.X11-unix
        working_dir: /openpilot-bridge
    inference-can-bridge:
        build:
            args:
                GROUP_ID: ${GROUP_ID}
                USER_ID: ${USER_ID}
            context: ${HOME}/repos/inference-node-bridge
            dockerfile: docker/Dockerfile
        command: bash -c "tmux new -d -s default; tmux send-keys '/root/mypython -u /inference-node-bridge/inference_can_bridge_node.py' ENTER; bash"
        environment:
            DEBUG_INFERENCE_NODE_BRIDGE: ${DEBUG_INFERENCE_NODE_BRIDGE}
            DISPLAY: ${DISPLAY}
            PYTHONPATH: /inference-node-bridge
            PYTHONUNBUFFERED: 1
            QT_X11_NO_MITSHM: 1
        network_mode: host
        stdin_open: true
        stop_grace_period: 100ms
        tty: true
        user: user
        volumes:
            - ${HOME}/repos/inference-node-bridge:/inference-node-bridge
        working_dir: /inference-node-bridge
